# This is an example configuration file for moombox.
# The configuration file is optional; the application will continue to run without one.
# Depending on how moombox is configured, the location of `config.toml` will vary.
# 
# Note that many of the example values are system-dependent, so you should not be copying this
# file and expecting it all to work.

# Controls the granularity of logs displayed in the standard error stream (incl. Hypercorn).
# The lower the value, the more verbose the log outputs.
# Refer to the numeric values in https://docs.python.org/3/library/logging.html#logging-levels
log_level = 30

[downloader]
# Controls options within moonarchive, the underlying downloading tool.
# Changes to the downloader options will only take effect on new downloads.

# Overrides the ffmpeg binary used for muxing outputs.
# Omitting this uses the ffmpeg resolved by PATH.
ffmpeg_path = "/opt/ffmpeg-custom/bin/ffmpeg"

# On Windows, use single quotes to ensure backslashes aren't treated as escape sequences:
# ffmpeg_path = 'C:\ffmpeg-7.1-full_build\bin\ffmpeg.exe'

# Maximum number of downloads to have in-flight for each stream (each broadcast has at least
# one video and one audio stream).
num_parallel_downloads = 1

# Use proof-of-origin when making requests.
# See https://github.com/nosoop/moonarchive?tab=readme-ov-file#proof-of-origin-downloads
# Visitor data is expected to have escaped "%3D" sequences in place of "=", while POTokens have
# "=" directly.
po_token = "long-base64-encoded-value-here"
visitor_data = "shorter-escaped-base64-value-here"

[[notifications]]
# Notifications are handled by apprise, so refer to the supported notifications for the syntax:
# https://github.com/caronc/apprise?tab=readme-ov-file#supported-notifications
# 
# You may define as many notification targets as you'd like.
url = "discord://webhook_id/webhook_token"

# moombox broadcasts notifications based on tags.
# Tags have a category prefix:
#   - 'status' prefix are for notifications sent on download task status change
#   - 'monitor-feed' prefix for when upcoming streams matching criteria are detected
tags = [ "status:downloading", "status:finished", "status:error", "monitor-feed:found" ]

[[channels]]
# moombox is able to poll the RSS feed for upcoming streams with title / description matches.
# 
# Feeds are currently polled every 10 minutes and will always reflect the current version of the
# configuration file.
id = "UCW5uhrG1eCBYditmhL0Ykjw"

# A friendly name may be specified for notifications; otherwise it will use the channel name.
name = "Elizabeth Rose Bloodflame"

# The 'terms' table maps key phrases to regular expressions to scan for in upcoming streams'
# titles and descriptions.  Notifications will indicate which terms are present.
# 
# IMPORTANT:  If no terms are provided, no streams will be automatically downloaded!  To
# download every stream, use a wildcard entry `terms."(all)" = '(.*)'`.
terms."karaoke" = '(?i)(\W|^)karaoke'
terms."unarchived" = '(?i)(\W|^)unar?chived?'
terms."rebroadcast" = '(?i)(\W|^)re-?broadcast'

# Determines how many older video items to scan through to identify lines that are unique to
# a given video.  This attempts to reduce false positives when a streamer uses some default
# boilerplate that includes keyword matches.
num_desc_lookbehind = 2
