---
services:
  moombox:
    container_name: moombox
    image: ghcr.io/nosoop/moombox
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      # - ./youtube.com_cookies.txt:/cookies.txt # optional cookie file, use to download members-only content
      - ./config.example.toml:/data/config/config.toml # config file
      - ./data/tmp:/opt/moombox/staging # config downloader.staging_directory
      - ./data/video:/opt/moombox/output # config downloader.output_directory
